#!/usr/bin/env bash
# Emit lua_exports.S: re-export the game's Lua 5.1 C-API symbols as ABSOLUTE
# dynamic symbols at their fixed addresses in the non-PIE Breach binary.
#
# The game (ET_EXEC, unstripped) defines every lua_*/luaL_*/luaopen_* at a fixed
# address in its .symtab but does NOT export them dynamically. Native mod .so's
# (ftldat, itb_io, libitbsdl) are built in mlua "module" mode / with Lua left
# undefined, so their undefined lua_* must resolve to the game's single runtime.
#
# For each symbol NAME at ADDR we emit:
#     .globl NAME
#     .type NAME, @function
#     .set NAME, 0xADDR
# which defines NAME as a globally-visible ABSOLUTE symbol. Linked into
# libitbboot.so (default visibility) it lands in .dynsym as an ABS definition;
# the dynamic linker binds other objects' undefined lua_* to these fixed
# addresses. Because they are ABS, the loader does not add libitbboot's load
# base -- the value is the game's real runtime address (no ASLR slide, non-PIE).
set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <path-to-Breach-binary>" >&2
	exit 1
fi

breach_bin="$1"
if [[ ! -f "$breach_bin" ]]; then
	echo "Error: '$breach_bin' does not exist" >&2
	exit 1
fi

out="$(dirname "$0")/lua_exports.S"

{
	echo "/* Generated by gen_lua_exports.sh from the Breach binary. Do not edit. */"
	echo "/* Re-exports the game's Lua 5.1 C API as absolute dynamic symbols so"
	echo " * mod .so's resolve their undefined lua_* to the game's single runtime. */"
	echo "	.text"
} >"$out"

# Public Lua C API: lua_*, luaL_*, luaopen_*. Type T (external) or t (local);
# include both so nothing the mods reference is missed.
nm "$breach_bin" |
	grep -E '^[0-9a-f]+ [Tt] (lua_|luaL_|luaopen_)' |
	sort -u -k3 |
	while read -r addr _type name; do
		{
			echo "	.globl $name"
			echo "	.type $name, @function"
			echo "	.set $name, 0x$addr"
		} >>"$out"
	done

count=$(grep -c '\.globl' "$out")
echo "Generated $out with $count exported Lua symbols from $breach_bin"
