#!/usr/bin/env bash
# Extract Lua function and global variable addresses from the Breach binary.
# Generates itbboot/lua_addrs.h for use in the preload bootstrap.
set -euo pipefail

if [[ $# -ne 1 ]]; then
	echo "Usage: $0 <path-to-Breach-binary>" >&2
	exit 1
fi

breach_bin="$1"

if [[ ! -f "$breach_bin" ]]; then
	echo "Error: '$breach_bin' does not exist" >&2
	exit 1
fi

# Extract static function addresses using nm.
# These are the lua_* functions the injected loadlib needs.
extract_addr() {
	local symbol="$1"
	nm "$breach_bin" | grep -E "^[0-9a-f]+ T $symbol\$" |
		awk '{print $1}' || echo "00000000"
}

# Extract the address of a C++ mangled symbol.
extract_mangled_addr() {
	local mangled="$1"
	nm "$breach_bin" | grep -E "^[0-9a-f]+ T $mangled\$" |
		awk '{print $1}' || echo "00000000"
}

# Get addresses for the lua functions.
lua_pushcclosure=$(extract_addr "lua_pushcclosure")
lua_setfield=$(extract_addr "lua_setfield")
lua_getfield=$(extract_addr "lua_getfield")
lua_pushstring=$(extract_addr "lua_pushstring")
lua_pushnil=$(extract_addr "lua_pushnil")
lua_pushvalue=$(extract_addr "lua_pushvalue")
lua_gettop=$(extract_addr "lua_gettop")
lua_settop=$(extract_addr "lua_settop")
lua_tolstring=$(extract_addr "lua_tolstring")
lua_call=$(extract_addr "lua_call")
lua_pcall=$(extract_addr "lua_pcall")
lua_error=$(extract_addr "lua_error")
luaL_error=$(extract_addr "luaL_error")
luaL_newstate=$(extract_addr "luaL_newstate")

# Get address for luabind::get_main_thread (C++ mangled).
get_main_thread=$(extract_mangled_addr "_ZN7luabind15get_main_threadEP9lua_State")

# Generate the header file.
cat >"$(dirname "$0")/lua_addrs.h" <<EOF
/* Generated by gen_lua_addrs.sh from $breach_bin
 * Static function and global variable addresses for Lua 5.1 in the Into the Breach binary.
 * Non-PIE binary (ET_EXEC), so addresses are stable across runs.
 */

#ifndef ITBBOOT_LUA_ADDRS_H
#define ITBBOOT_LUA_ADDRS_H

#include <stdint.h>

/* Lua 5.1 static function addresses (from nm -g Breach) */
#define LUA_PUSHCCLOSURE ((uintptr_t)0x${lua_pushcclosure})
#define LUA_SETFIELD ((uintptr_t)0x${lua_setfield})
#define LUA_GETFIELD ((uintptr_t)0x${lua_getfield})
#define LUA_PUSHSTRING ((uintptr_t)0x${lua_pushstring})
#define LUA_PUSHNIL ((uintptr_t)0x${lua_pushnil})
#define LUA_PUSHVALUE ((uintptr_t)0x${lua_pushvalue})
#define LUA_GETTOP ((uintptr_t)0x${lua_gettop})
#define LUA_SETTOP ((uintptr_t)0x${lua_settop})
#define LUA_TOLSTRING ((uintptr_t)0x${lua_tolstring})
#define LUA_CALL ((uintptr_t)0x${lua_call})
#define LUA_PCALL ((uintptr_t)0x${lua_pcall})
#define LUA_ERROR ((uintptr_t)0x${lua_error})
#define LUAL_ERROR ((uintptr_t)0x${luaL_error})
#define LUAL_NEWSTATE ((uintptr_t)0x${luaL_newstate})

/* luabind::get_main_thread C++ function (mangled) */
#define GET_MAIN_THREAD ((uintptr_t)0x${get_main_thread})

/* Function pointer typedefs for type-safe calls */
typedef int (*lua_pushcclosure_fn)(void *L, void *f, int n);
typedef void (*lua_setfield_fn)(void *L, int idx, const char *k);
typedef int (*lua_getfield_fn)(void *L, int idx, const char *k);
typedef const char *(*lua_pushstring_fn)(void *L, const char *s);
typedef void (*lua_pushnil_fn)(void *L);
typedef void (*lua_pushvalue_fn)(void *L, int idx);
typedef int (*lua_gettop_fn)(void *L);
typedef void (*lua_settop_fn)(void *L, int idx);
typedef const char *(*lua_tolstring_fn)(void *L, int idx, size_t *len);
typedef void (*lua_call_fn)(void *L, int nargs, int nresults);
typedef int (*lua_pcall_fn)(void *L, int nargs, int nresults, int errfunc);
typedef int (*lua_error_fn)(void *L);
typedef int (*luaL_error_fn)(void *L, const char *fmt, ...);
typedef void *(*luaL_newstate_fn)(void);

#endif /* ITBBOOT_LUA_ADDRS_H */
EOF

echo "Generated $(dirname "$0")/lua_addrs.h from $breach_bin"
