/* libitbboot.so - LD_PRELOAD bootstrap injecting a dlopen-based package.loadlib.
 *
 * The native Linux Breach binary embeds PUC Lua 5.1.5 built without
 * LUA_DL_DLOPEN: package.loadlib is a stub that fails with "dynamic libraries
 * not enabled", and the binary imports only dlsym, never dlopen. So no .so can
 * be loaded from Lua as the loader expects. This preload fixes that:
 *
 *   1. Capture the game's lua_State (L) deterministically via a one-shot inline
 *      hook on lua_getfield @ 0x9f273c. Its prologue moves the first argument
 *      (RDI == L) to the stack, so RDI holds L on entry. The hook stashes RDI
 *      into g_L, restores the original prologue, and re-runs the real function
 *      unhooked (restore-and-restart; no trampoline relocation needed). Early
 *      Lua init is single-threaded, so the restore race is benign.
 *   2. Inject from a libc interposer, NOT from inside the hook (reentrancy is
 *      unsafe). The game imports both fopen and open; on the first script open
 *      (path under "scripts/") with L captured, install our loadlib and mark it
 *      done. This runs on the libc stack, outside any lua_* call, so calling
 *      lua_setfield is safe.
 *   3. our_loadlib dlopen()s the path and dlsym()s the entry symbol, returning
 *      the entry as a C function (PUC semantics: on failure nil,msg,"open"|"init").
 *
 * The lua_* functions are the game's own static functions at fixed absolute
 * addresses (non-PIE ET_EXEC binary, no ASLR slide), called as function
 * pointers -- zero ABI risk. See lua_addrs.h (generated by gen_lua_addrs.sh).
 */

#define _GNU_SOURCE
#include <dlfcn.h>
#include <errno.h>
#include <fcntl.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#include "lua_addrs.h"

/* LUA_GLOBALSINDEX in Lua 5.1 (pseudo-index for the globals table). */
#define LUA_GLOBALSINDEX (-10002)

/* Hidden visibility forces local binding so the file-scope asm stub can
 * reference these via direct PC-relative access (no GOT/PLT indirection). */
#define HIDDEN __attribute__((visibility("hidden")))

/* Captured game lua_State. Written by the capture stub, read by the injector
 * and the SDL interposer. */
HIDDEN void *g_L = NULL;

/* Absolute address of the real lua_getfield, loaded by the stub to resume. */
HIDDEN __attribute__((used)) void *g_getfield_addr = (void *)LUA_GETFIELD;

/* Original 12 bytes of the lua_getfield prologue, saved before patching. */
HIDDEN __attribute__((used)) unsigned char g_orig_bytes[12];

static int g_injected = 0;

/* Real libc entry points resolved via dlsym(RTLD_NEXT, ...). */
static FILE *(*real_fopen)(const char *, const char *) = NULL;
static FILE *(*real_fopen64)(const char *, const char *) = NULL;
static int (*real_open)(const char *, int, ...) = NULL;
static int (*real_open64)(const char *, int, ...) = NULL;

/* ---- logging -------------------------------------------------------------- */

/* Append to a dedicated itbboot.log using the *real* fopen (never the
 * interposer, to avoid reentering the injection path). A separate file keeps
 * these diagnostics from being clobbered by the game's own writes to log.txt
 * (both processes hold independent handles to the same file otherwise).
 * Falls back to stderr. */
static void itbboot_log(const char *fmt, ...) {
	if (!real_fopen) {
		real_fopen = dlsym(RTLD_NEXT, "fopen");
	}
	FILE *fp = NULL;
	const char *home = getenv("HOME");
	if (home && real_fopen) {
		char path[512];
		snprintf(path, sizeof(path), "%s/.local/share/IntoTheBreach/itbboot.log", home);
		fp = real_fopen(path, "a");
	}
	if (!fp) {
		fp = stderr;
	}
	va_list ap;
	va_start(ap, fmt);
	fprintf(fp, "[itbboot] ");
	vfprintf(fp, fmt, ap);
	fprintf(fp, "\n");
	va_end(ap);
	fflush(fp);
	if (fp != stderr) {
		fclose(fp);
	}
}

/* ---- injected package.loadlib -------------------------------------------- */

/* our_loadlib(path, symbol) -> entry function | (nil, message, "open"|"init").
 * PUC loadlib semantics, backed by dlopen/dlsym. */
static int itbboot_loadlib_cfunc(void *L) {
	lua_gettop_fn lua_gettop = (lua_gettop_fn)LUA_GETTOP;
	lua_tolstring_fn lua_tolstring = (lua_tolstring_fn)LUA_TOLSTRING;
	lua_pushnil_fn lua_pushnil = (lua_pushnil_fn)LUA_PUSHNIL;
	lua_pushstring_fn lua_pushstring = (lua_pushstring_fn)LUA_PUSHSTRING;
	lua_pushcclosure_fn lua_pushcclosure = (lua_pushcclosure_fn)LUA_PUSHCCLOSURE;

	if (lua_gettop(L) < 2) {
		lua_pushnil(L);
		lua_pushstring(L, "loadlib: expected (path, symbol)");
		lua_pushstring(L, "open");
		return 3;
	}

	const char *path = lua_tolstring(L, 1, NULL);
	const char *sym = lua_tolstring(L, 2, NULL);
	if (!path || !sym) {
		lua_pushnil(L);
		lua_pushstring(L, "loadlib: path and symbol must be strings");
		lua_pushstring(L, "open");
		return 3;
	}

	void *h = dlopen(path, RTLD_NOW | RTLD_GLOBAL);
	if (!h) {
		const char *err = dlerror();
		itbboot_log("dlopen failed for %s: %s", path, err ? err : "(null)");
		lua_pushnil(L);
		lua_pushstring(L, err ? err : "dlopen failed");
		lua_pushstring(L, "open");
		return 3;
	}

	void *f = dlsym(h, sym);
	if (!f) {
		const char *err = dlerror();
		itbboot_log("dlsym failed for %s in %s: %s", sym, path, err ? err : "(null)");
		dlclose(h);
		lua_pushnil(L);
		lua_pushstring(L, err ? err : "dlsym failed");
		lua_pushstring(L, "init");
		return 3;
	}

	lua_pushcclosure(L, f, 0);
	itbboot_log("loadlib: %s:%s -> %p", path, sym, f);
	return 1;
}

/* Replace package.loadlib in the game's globals with our C closure. Runs on the
 * libc interposer stack, so calling into the game's Lua is safe. */
static void itbboot_inject(void *L) {
	lua_getfield_fn lua_getfield = (lua_getfield_fn)LUA_GETFIELD;
	lua_pushcclosure_fn lua_pushcclosure = (lua_pushcclosure_fn)LUA_PUSHCCLOSURE;
	lua_setfield_fn lua_setfield = (lua_setfield_fn)LUA_SETFIELD;
	lua_gettop_fn lua_gettop = (lua_gettop_fn)LUA_GETTOP;
	lua_settop_fn lua_settop = (lua_settop_fn)LUA_SETTOP;

	int top0 = lua_gettop(L);
	lua_getfield(L, LUA_GLOBALSINDEX, "package");
	lua_pushcclosure(L, (void *)itbboot_loadlib_cfunc, 0);
	lua_setfield(L, -2, "loadlib");
	lua_settop(L, top0);
	itbboot_log("inject: package.loadlib replaced (L=%p)", L);
}

/* ---- one-shot inline hook on lua_getfield -------------------------------- */

/* Restore the original lua_getfield prologue. Called from the capture stub
 * (via the naked-preserving push/pop wrapper) after L is stashed. */
HIDDEN __attribute__((used)) void itbboot_restore_getfield(void) {
	unsigned char *dst = (unsigned char *)LUA_GETFIELD;
	for (int i = 0; i < 12; i++) {
		dst[i] = g_orig_bytes[i];
	}
	__builtin___clear_cache((char *)dst, (char *)dst + 12);
}

/* The capture stub. Entered via the patched jump at lua_getfield: RDI holds L.
 * Stashes L, restores the original prologue, then jumps to the real function so
 * it re-executes unhooked. Only RAX/flags are clobbered as far as the real
 * function is concerned (all arg registers are push/pop preserved around the
 * restore helper call).
 *
 * IMPORTANT: The number of pushes MUST remain ODD so RSP ≡ 0 (mod 16) at the
 * 'call itbboot_restore_getfield' instruction (SysV AMD64 ABI requirement).
 * Currently: 9 pushes (odd) = correct alignment. */
extern void itbboot_capture_stub(void);
__asm__(
	".text\n\t"
	".globl itbboot_capture_stub\n\t"
	".hidden itbboot_capture_stub\n"
	"itbboot_capture_stub:\n\t"
	"movq %rdi, g_L(%rip)\n\t"
	"pushq %rax\n\t"
	"pushq %rdi\n\t"
	"pushq %rsi\n\t"
	"pushq %rdx\n\t"
	"pushq %rcx\n\t"
	"pushq %r8\n\t"
	"pushq %r9\n\t"
	"pushq %r10\n\t"
	"pushq %r11\n\t"
	"call itbboot_restore_getfield\n\t"
	"popq %r11\n\t"
	"popq %r10\n\t"
	"popq %r9\n\t"
	"popq %r8\n\t"
	"popq %rcx\n\t"
	"popq %rdx\n\t"
	"popq %rsi\n\t"
	"popq %rdi\n\t"
	"popq %rax\n\t"
	"movq g_getfield_addr(%rip), %rax\n\t"
	"jmp *%rax\n\t");

/* Check if the current process is the Breach game binary.
 * Returns 1 if this is Breach, 0 otherwise. */
static int itbboot_is_breach(void) {
	char exepath[256];
	ssize_t n = readlink("/proc/self/exe", exepath, sizeof(exepath) - 1);
	if (n < 0 || n >= (ssize_t)(sizeof(exepath) - 1)) {
		itbboot_log("readlink /proc/self/exe failed or path too long");
		return 0;
	}
	exepath[n] = '\0';

	/* Extract the basename and check if it's "Breach". */
	const char *basename = exepath;
	for (const char *p = exepath; *p; p++) {
		if (*p == '/') {
			basename = p + 1;
		}
	}
	int is_breach = (strcmp(basename, "Breach") == 0);
	if (!is_breach) {
		itbboot_log("process is not Breach (exe: %s); skipping hook", exepath);
	}
	return is_breach;
}

/* Verify that the bytes at addr match the expected lua_getfield prologue.
 * Expected prologue: 55 48 89 e5 48 83 ec 40 48 89 7d d8
 * Returns 1 if they match, 0 otherwise. */
static int itbboot_verify_prologue(uintptr_t addr) {
	static const unsigned char expected[] = {
		0x55, 0x48, 0x89, 0xE5, 0x48, 0x83, 0xEC, 0x40,
		0x48, 0x89, 0x7D, 0xD8
	};
	unsigned char *dst = (unsigned char *)addr;
	for (int i = 0; i < 12; i++) {
		if (dst[i] != expected[i]) {
			itbboot_log("prologue mismatch at %p[%d]: expected 0x%02x, found 0x%02x",
				(void *)addr, i, expected[i], dst[i]);
			return 0;
		}
	}
	return 1;
}

/* Patch lua_getfield's first 12 bytes with `movabs rax, stub; jmp rax`. */
static void itbboot_install_hook(void) {
	uintptr_t addr = LUA_GETFIELD;

	/* Guard 1: Only patch in the Breach process. */
	if (!itbboot_is_breach()) {
		return;
	}

	/* Guard 2: Verify the prologue before patching (self-checking). */
	if (!itbboot_verify_prologue(addr)) {
		itbboot_log("prologue verification failed at %p; skipping hook", (void *)addr);
		return;
	}

	long ps = sysconf(_SC_PAGESIZE);
	if (ps <= 0) {
		ps = 4096;
	}
	uintptr_t mask = (uintptr_t)ps - 1;
	uintptr_t start = addr & ~mask;
	uintptr_t end = (addr + 12 + mask) & ~mask;
	/* Make .text page RWX for the duration of the process. The stub's
	 * itbboot_restore_getfield restores and may rewrite the original prologue,
	 * so this page must remain writable for the lifetime of the hook. This
	 * trades W^X hardening for the dynamic patching architecture.
	 * Ideally, we would re-protect to RX after installation, but that would
	 * require single-step tracing or other complex mechanisms during restore. */
	if (mprotect((void *)start, end - start, PROT_READ | PROT_WRITE | PROT_EXEC) != 0) {
		itbboot_log("mprotect RWX failed at %p: %s -- hook NOT installed", (void *)start,
			strerror(errno));
		return;
	}

	unsigned char *dst = (unsigned char *)addr;
	memcpy(g_orig_bytes, dst, 12);

	uint64_t stub = (uint64_t)(uintptr_t)&itbboot_capture_stub;
	unsigned char patch[12];
	patch[0] = 0x48; /* movabs rax, imm64 */
	patch[1] = 0xB8;
	memcpy(patch + 2, &stub, 8);
	patch[10] = 0xFF; /* jmp rax */
	patch[11] = 0xE0;
	memcpy(dst, patch, 12);
	__builtin___clear_cache((char *)dst, (char *)dst + 12);

	itbboot_log("installed lua_getfield hook @ %p -> stub %p (mprotect RWX ok)", dst,
		(void *)stub);
}

/* ---- libc interposers ----------------------------------------------------- */

static void itbboot_maybe_inject(const char *path) {
	if (g_injected || !g_L || !path) {
		return;
	}
	if (!strstr(path, "scripts/")) {
		return;
	}
	g_injected = 1;
	itbboot_log("first scripts/ open (%s); injecting loadlib", path);
	itbboot_inject(g_L);
}

FILE *fopen(const char *path, const char *mode) {
	if (!real_fopen) {
		real_fopen = dlsym(RTLD_NEXT, "fopen");
	}
	itbboot_maybe_inject(path);
	return real_fopen(path, mode);
}

FILE *fopen64(const char *path, const char *mode) {
	if (!real_fopen64) {
		real_fopen64 = dlsym(RTLD_NEXT, "fopen64");
	}
	itbboot_maybe_inject(path);
	return real_fopen64(path, mode);
}

int open(const char *path, int flags, ...) {
	if (!real_open) {
		real_open = dlsym(RTLD_NEXT, "open");
	}
	itbboot_maybe_inject(path);
	if (flags & O_CREAT) {
		va_list ap;
		va_start(ap, flags);
		int mode = va_arg(ap, int);
		va_end(ap);
		return real_open(path, flags, mode);
	}
	return real_open(path, flags);
}

int open64(const char *path, int flags, ...) {
	if (!real_open64) {
		real_open64 = dlsym(RTLD_NEXT, "open64");
	}
	itbboot_maybe_inject(path);
	if (flags & O_CREAT) {
		va_list ap;
		va_start(ap, flags);
		int mode = va_arg(ap, int);
		va_end(ap);
		return real_open64(path, flags, mode);
	}
	return real_open64(path, flags);
}

/* ---- SDL/GL frame-hook forwarding interposers ----------------------------- */

/* libitbsdl's rendering hooks fire from here. Interposing the SDL/GL symbols
 * directly inside the big, dual-loaded libitbsdl never fired during real
 * rendering; interposing from this thin, first-loaded preload does. Each shim
 * resolves the real function once via dlsym(RTLD_NEXT, ...) and forwards into
 * libitbsdl's exported itbsdl_dispatch_* entry point.
 *
 * libitbsdl is loaded via the injected package.loadlib (RTLD_GLOBAL) only after
 * the first frames render, so its dispatch exports are not resolvable at process
 * start. Each shim retries dlsym(RTLD_DEFAULT, ...) every call while the pointer
 * is still NULL, then caches it -- so the hooks begin working the moment
 * libitbsdl loads mid-run, and early frames simply pass through to the real
 * function. Pure C, plain ABI-matching types: no SDL/GL headers here. */

void SDL_GL_SwapWindow(void *window) {
	static void (*real)(void *) = NULL;
	if (!real) {
		real = dlsym(RTLD_NEXT, "SDL_GL_SwapWindow");
	}
	static void (*disp)(void) = NULL;
	if (!disp) {
		disp = dlsym(RTLD_DEFAULT, "itbsdl_dispatch_swapwindow");
	}
	if (disp) {
		disp();  // overlay/draw pass BEFORE the real swap
	}
	real(window);
}

int SDL_PollEvent(void *evt) {
	static int (*real)(void *) = NULL;
	if (!real) {
		real = dlsym(RTLD_NEXT, "SDL_PollEvent");
	}
	static int (*disp)(void *) = NULL;
	if (!disp) {
		disp = dlsym(RTLD_DEFAULT, "itbsdl_dispatch_event");
	}
	if (!disp || !evt) {
		return real(evt);
	}
	for (;;) {
		int r = real(evt);
		if (!r) {
			return 0;
		}
		if (!disp(evt)) {
			return 1;  // unconsumed -> hand this event to the game
		}
		/* consumed by a hook -> keep pulling */
	}
}

void glBindTexture(unsigned int target, unsigned int texture) {
	static void (*real)(unsigned int, unsigned int) = NULL;
	if (!real) {
		real = dlsym(RTLD_NEXT, "glBindTexture");
	}
	static void (*disp)(unsigned int, unsigned int) = NULL;
	if (!disp) {
		disp = dlsym(RTLD_DEFAULT, "itbsdl_dispatch_bindtexture");
	}
	if (disp) {
		disp(target, texture);  // track before the real bind (matches old order)
	}
	real(target, texture);
}

void glTexImage2D(unsigned int target, int level, int internalformat, int width,
	int height, int border, unsigned int format, unsigned int type,
	const void *pixels) {
	static void (*real)(unsigned int, int, int, int, int, int, unsigned int,
		unsigned int, const void *) = NULL;
	if (!real) {
		real = dlsym(RTLD_NEXT, "glTexImage2D");
	}
	static void (*disp)(unsigned int, int, int, int, unsigned int, const void *) = NULL;
	if (!disp) {
		disp = dlsym(RTLD_DEFAULT, "itbsdl_dispatch_teximage2d");
	}
	if (disp) {
		disp(target, internalformat, width, height, format, pixels);
	}
	real(target, level, internalformat, width, height, border, format, type, pixels);
}

void glDrawArrays(unsigned int mode, int first, int count) {
	static void (*real)(unsigned int, int, int) = NULL;
	if (!real) {
		real = dlsym(RTLD_NEXT, "glDrawArrays");
	}
	static void (*disp)(void) = NULL;
	if (!disp) {
		disp = dlsym(RTLD_DEFAULT, "itbsdl_dispatch_draw");
	}
	if (disp) {
		disp();
	}
	real(mode, first, count);
}

void glDrawElements(unsigned int mode, int count, unsigned int type,
	const void *indices) {
	static void (*real)(unsigned int, int, unsigned int, const void *) = NULL;
	if (!real) {
		real = dlsym(RTLD_NEXT, "glDrawElements");
	}
	static void (*disp)(void) = NULL;
	if (!disp) {
		disp = dlsym(RTLD_DEFAULT, "itbsdl_dispatch_draw");
	}
	if (disp) {
		disp();
	}
	real(mode, count, type, indices);
}

/* ---- init ----------------------------------------------------------------- */

__attribute__((constructor)) static void itbboot_init(void) {
	fprintf(stderr, "[itbboot] libitbboot.so loaded\n");
	fflush(stderr);
	itbboot_log("constructor: installing lua_getfield capture hook");
	itbboot_install_hook();
}
