/* Generated by gen_lua_addrs.sh from /var/mnt/2891f9ef-34b4-4d43-9dbf-c91b2ac9c36e/SteamLibrary/steamapps/common/Into the Breach/Breach
 * Static function and global variable addresses for Lua 5.1 in the Into the Breach binary.
 * Non-PIE binary (ET_EXEC), so addresses are stable across runs.
 */

#ifndef ITBBOOT_LUA_ADDRS_H
#define ITBBOOT_LUA_ADDRS_H

#include <stdint.h>

/* Lua 5.1 static function addresses (from nm -g Breach) */
#define LUA_PUSHCCLOSURE ((uintptr_t)0x00000000009f24e2)
#define LUA_SETFIELD ((uintptr_t)0x00000000009f2b76)
#define LUA_GETFIELD ((uintptr_t)0x00000000009f273c)
#define LUA_PUSHSTRING ((uintptr_t)0x00000000009f2353)
#define LUA_PUSHNIL ((uintptr_t)0x00000000009f2207)
#define LUA_PUSHVALUE ((uintptr_t)0x00000000009f1a9e)
#define LUA_GETTOP ((uintptr_t)0x00000000009f16f4)
#define LUA_SETTOP ((uintptr_t)0x00000000009f171b)
#define LUA_TOLSTRING ((uintptr_t)0x00000000009f1f3a)
#define LUA_CALL ((uintptr_t)0x00000000009f306b)
#define LUA_PCALL ((uintptr_t)0x00000000009f3125)
#define LUA_ERROR ((uintptr_t)0x00000000009f358c)
#define LUAL_ERROR ((uintptr_t)0x00000000009f3d2a)
#define LUAL_NEWSTATE ((uintptr_t)0x00000000009f536a)

/* luabind::get_main_thread C++ function (mangled) */
#define GET_MAIN_THREAD ((uintptr_t)0x0000000000a15988)

/* Function pointer typedefs for type-safe calls */
typedef int (*lua_pushcclosure_fn)(void *L, void *f, int n);
typedef void (*lua_setfield_fn)(void *L, int idx, const char *k);
typedef int (*lua_getfield_fn)(void *L, int idx, const char *k);
typedef const char *(*lua_pushstring_fn)(void *L, const char *s);
typedef void (*lua_pushnil_fn)(void *L);
typedef void (*lua_pushvalue_fn)(void *L, int idx);
typedef int (*lua_gettop_fn)(void *L);
typedef void (*lua_settop_fn)(void *L, int idx);
typedef const char *(*lua_tolstring_fn)(void *L, int idx, size_t *len);
typedef void (*lua_call_fn)(void *L, int nargs, int nresults);
typedef int (*lua_pcall_fn)(void *L, int nargs, int nresults, int errfunc);
typedef int (*lua_error_fn)(void *L);
typedef int (*luaL_error_fn)(void *L, const char *fmt, ...);
typedef void *(*luaL_newstate_fn)(void);

#endif /* ITBBOOT_LUA_ADDRS_H */
